// Static build for the "Automations in T3 Code" mockup site.
//
//   node tools/build.mjs            → generates js/icons.js, js/palettes.js and styles.css
//   node tools/build.mjs --watch    → rebuilds styles.css when index.html / js/** / theme.css change
//
// Nothing is installed here: tailwindcss + lucide are borrowed from the decompiled Automations UI
// app's node_modules, and the T3 Code theme palettes are read straight out of the a3 code repo
// (Node strips the TypeScript types when importing that file).
import { createRequire } from "node:module";
import { readFileSync, writeFileSync, watch, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(here, "..");
const PROJECT = resolve(ROOT, "../..");
const APP_NODE_MODULES = join(PROJECT, "Automations UI/app/node_modules");
const T3_PALETTES = join(PROJECT, "a3 code/packages/shared/src/themePalettes.ts");
const req = createRequire(join(APP_NODE_MODULES, "x.js"));
const { compile, optimize } = await import(pathToFileURL(req.resolve("@tailwindcss/node")).href);
const { Scanner } = req("@tailwindcss/oxide");

/* ------------------------------------------------------------------ icons */
// Lucide icons used by the mockup (kebab-case file names in lucide-react/dist/esm/icons).
const LUCIDE = [
  "activity", "alarm-clock", "arrow-left", "arrow-right", "arrow-up-right", "bell", "bug", "calendar",
  "calendar-days", "camera", "chart-column", "chart-no-axes-column", "check", "chevron-down", "chevron-left",
  "chevron-right", "chevron-up", "chevrons-up-down", "circle-check", "circle-dashed", "circle-x", "clock",
  "copy", "ellipsis", "ellipsis-vertical", "external-link", "file-text", "filter", "folder", "folder-git-2",
  "folder-plus", "git-pull-request", "heart-pulse", "history", "info", "layers", "layout-template",
  "list-filter", "loader", "lock", "mail", "message-square", "monitor", "package", "panel-left", "pencil",
  "play", "plus", "refresh-cw", "repeat", "rotate-ccw", "search", "settings", "settings-2", "shield-check",
  "sliders-horizontal", "sparkles", "square-pen", "sun", "moon", "tag", "tags", "terminal", "test-tube",
  "timer", "trash-2", "triangle-alert", "webhook", "workflow", "wrench", "x", "zap", "arrow-down-up",
  "circle", "check-check", "pause", "square", "git-branch", "box", "cpu", "globe", "hash", "user-round",
  "users", "inbox", "bot", "brain", "file-code", "list", "eye", "eye-off", "key-round", "link", "pin",
  "undo-2", "chevrons-right", "arrow-down", "arrow-up", "minus", "dot", "bell-ring", "hourglass",
  "circle-alert", "circle-play", "square-terminal", "code", "database", "server", "laptop", "cloud",
];

async function buildIcons() {
  const out = {};
  for (const name of LUCIDE) {
    const file = join(APP_NODE_MODULES, "lucide-react/dist/esm/icons", `${name}.mjs`);
    let src;
    try { src = readFileSync(file, "utf8"); } catch { console.warn(`[icons] missing lucide icon: ${name}`); continue; }
    const m = src.match(/const __iconNode = (\[[\s\S]*?\]);\n/);
    if (!m) { console.warn(`[icons] could not parse ${name}`); continue; }
    // The node array is plain JSON-ish JS: ["path", { d: "...", key: "..." }]
    const node = new Function(`return ${m[1]}`)();
    out[name] = node
      .map(([tag, attrs]) => {
        const a = Object.entries(attrs).filter(([k]) => k !== "key").map(([k, v]) => `${k}="${v}"`).join(" ");
        return `<${tag} ${a}/>`;
      })
      .join("");
  }
  const body = `// Generated by tools/build.mjs — lucide ${req("lucide-react/package.json").version} icon bodies.\n` +
    `// Usage: icon("calendar", "size-4") → <svg …>. Attributes mirror lucide's defaults (24px box, 2px round strokes).\n` +
    `window.LUCIDE = ${JSON.stringify(out, null, 0)};\n`;
  writeFileSync(join(ROOT, "js/icons.js"), body);
  console.log(`[icons] ${Object.keys(out).length} lucide icons → js/icons.js`);
}

/* --------------------------------------------------------------- palettes */
async function buildPalettes() {
  const mod = await import(pathToFileURL(T3_PALETTES).href);
  const themes = Object.values(mod).filter((v) => v && typeof v === "object" && "colors" in v && "id" in v);
  const compact = themes.map((t) => ({ id: t.id, label: t.label, appearance: t.appearance, colors: t.colors, variants: t.variants ?? {}, sidebarArtwork: t.sidebarArtwork ?? false }));
  const body = `// Generated by tools/build.mjs from a3 code/packages/shared/src/themePalettes.ts\n` +
    `window.T3_THEMES = ${JSON.stringify(compact)};\n`;
  writeFileSync(join(ROOT, "js/palettes.js"), body);
  console.log(`[palettes] ${compact.map((t) => t.id).join(", ")} → js/palettes.js`);
}

/* -------------------------------------------------------------------- css */
async function buildCss() {
  const t0 = performance.now();
  const css = readFileSync(join(ROOT, "theme.css"), "utf8");
  const compiler = await compile(css, {
    base: ROOT,
    onDependency: () => {},
    customCssResolver: async (id) => {
      if (id === "tailwindcss") return join(APP_NODE_MODULES, "tailwindcss/index.css");
      if (id.startsWith("tailwindcss/")) return join(APP_NODE_MODULES, id);
      return undefined;
    },
  });
  const scanner = new Scanner({
    sources: [
      { base: ROOT, pattern: "index.html", negated: false },
      { base: join(ROOT, "js"), pattern: "**/*.js", negated: false },
      { base: ROOT, pattern: "safelist.txt", negated: false },
    ],
  });
  const candidates = scanner.scan();
  const built = compiler.build(candidates);
  const { code } = optimize(built, { minify: false });
  writeFileSync(join(ROOT, "styles.css"), code);
  console.log(`[css] ${candidates.length} candidates → styles.css (${(code.length / 1024).toFixed(1)} KB) in ${Math.round(performance.now() - t0)}ms`);
}

await buildIcons();
await buildPalettes();
await buildCss();

if (process.argv.includes("--watch")) {
  let timer;
  const schedule = () => { clearTimeout(timer); timer = setTimeout(() => buildCss().catch((e) => console.error(e)), 80); };
  watch(join(ROOT, "js"), { recursive: true }, schedule);
  for (const f of ["index.html", "theme.css", "safelist.txt"]) { try { watch(join(ROOT, f), schedule); } catch {} }
  console.log("[build] watching…");
}
